//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NekoVpk {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class NekoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static NekoSettings defaultInstance = ((NekoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NekoSettings())));
        
        public static NekoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDir {
            get {
                return ((string)(this["GameDir"]));
            }
            set {
                this["GameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public short CompressionLevel {
            get {
                return ((short)(this["CompressionLevel"]));
            }
            set {
                this["CompressionLevel"] = value;
            }
        }
    }
}
